CREATE DATABASE QLCHTS
GO
USE QLCHTS
GO

CREATE TABLE NHANVIEN(
MANV VARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
NGAYSINH DATE,
CCCD VARCHAR(20) NOT NULL,
SDT VARCHAR(15) NOT NULL,
GIOITINH BIT NOT NULL,
USERNAME VARCHAR(30)NOT NULL ,
PASSWORD VARCHAR(30)NOT NULL,
ROLE BIT NOT NULL,
TRANGTHAI BIT,
GHICHU NVARCHAR(100)
)

CREATE TABLE KhachHang(
MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
SDT VARCHAR(12) ,
ANH NVARCHAR(30) ,
DIACHI NVARCHAR(50),
GHICHU NVARCHAR(100),
TRANGTHAI BIT NOT NULL
)
CREATE TABLE HOADON(
MAHD VARCHAR(10) PRIMARY KEY,
MANV VARCHAR(10),
MAKH VARCHAR(10),
NGAYGD DATETIME ,
HINHTHUCTHANHTOAN BIT,
HINHTHUCMUA BIT,
KHACHTRA MONEY,
TONGTIEN MONEY,
TRANGTHAIHD NVARCHAR(30)
)
CREATE TABLE DOITRA(
MAPDT VARCHAR(10) NOT NULL,
MAHD VARCHAR(10) NOT NULL,
MASP VARCHAR(10) NOT NULL,
HINHTHUC BIT NOT NULL,
LYDO NVARCHAR(100),
GHICHU NVARCHAR(100),
CONSTRAINT PK_DOITRA PRIMARY KEY (MAPDT)  
);

CREATE TABLE HOADONCHITIET(
MaSP varchar(10) not null,
MaHD varchar(10) not null,
SoLuong int not null,
TienCong money,
DonGia money not null,
GiamGia money,
ThanhTien money not null
CONSTRAINT HOADONCHITIET_Pk PRIMARY KEY (MAHD, MaSP)
);



CREATE TABLE DANHMUCSANPHAM(
MADM    VARCHAR(10) PRIMARY KEY,
TENDM   NVARCHAR(30),
MOTA    NVARCHAR(50)
)
CREATE TABLE CHATLIEU(
MACL   VARCHAR(10) PRIMARY KEY,
TENCL  VARCHAR(50),
MOTA   VARCHAR(50)
)
CREATE TABLE LOAICHATLIEU(
MALCL   VARCHAR(10) PRIMARY KEY,
MACL   VARCHAR(10),
TENLCL  VARCHAR(50),
GIABANRA MONEY,
GIAMUAVAO MONEY

)


CREATE TABLE SANPHAM(
MASP         VARCHAR(10) PRIMARY KEY,
MALCL         VARCHAR(10),
MADM         VARCHAR(10),
TENSP        NVARCHAR(50),
KHOILUONG    FLOAT,
GIANHAP      MONEY,
GIABAN       MONEY,
GiAMUAVAO    MONEY,
TIENCONG     MONEY,
TRANGTHAI    NVARCHAR(30),
SOLUONG      INT,
MOTA         NVARCHAR(50)
)

CREATE TABLE PHIEUNHAP(
MAPN               VARCHAR(10) PRIMARY KEY,
THANHTIEN          MONEY,
NGAYNHAP           DATE,
TRANGTHAIPHIEUNHAP BIT,
NOINHAP            NVARCHAR(50),
GHICHU             NVARCHAR(100),
)
CREATE TABLE CHITIETPHIEUNHAP(
MAPN      VARCHAR(10),
MASP      VARCHAR(10),
SL        INT ,
DONGIA    MONEY,
CONG      MONEY,
THANHTIEN MONEY,
);
ALTER TABLE HOADON  ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) 
ALTER TABLE HOADON  ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH) 
ALTER TABLE DOITRA  ADD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE HOADONCHITIET  ADD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD) 
ALTER TABLE HOADONCHITIET  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) 

ALTER TABLE SANPHAM  ADD FOREIGN KEY(MADM) REFERENCES DANHMUCSANPHAM(MADM) 
ALTER TABLE SANPHAM  ADD FOREIGN KEY(MALCL) REFERENCES LOAICHATLIEU(MALCL) 
ALTER TABLE LOAICHATLIEU  ADD FOREIGN KEY(MACL) REFERENCES CHATLIEU(MACL) 
ALTER TABLE CHITIETPHIEUNHAP  ADD FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN) 
ALTER TABLE CHITIETPHIEUNHAP  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) 
