CREATE DATABASE QLCHTS
GO
USE QLCHTS
GO

--drop database QLCHTS
Insert nhanvien values ('NV01','Sy','2002/03/24','9999999990','0987654',1,'SyHQ24','123',1,1,'KO')
CREATE TABLE NHANVIEN(
MANV VARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
NGAYSINH DATE,
CCCD VARCHAR(20) NOT NULL,
SDT VARCHAR(15) NOT NULL,
GIOITINH BIT NOT NULL,
USERNAME VARCHAR(30)NOT NULL ,
PASSWORD VARCHAR(30)NOT NULL,
ROLE BIT NOT NULL,
TRANGTHAI BIT,
GHICHU NVARCHAR(100)
)

CREATE TABLE KhachHang(
MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
SDT VARCHAR(12) ,
ANH NVARCHAR(30) ,
DIACHI NVARCHAR(50),
GHICHU NVARCHAR(100),
TRANGTHAI BIT NOT NULL
)
CREATE TABLE HOADON(
MAHD VARCHAR(10) PRIMARY KEY,
MANV VARCHAR(10),
MAKH VARCHAR(10),
NGAYGD DATETIME ,
HINHTHUCTHANHTOAN BIT,
HINHTHUCMUA BIT,
KHACHTRA MONEY,
TONGTIEN MONEY,
TRANGTHAIHD NVARCHAR(30)
)
CREATE TABLE DoiTra(
MaPDT varchar(10) not null,
MaHD varchar(10) not null,
MaSP varchar(10) not null,
HinhThuc bit not null,
LyDo Nvarchar(100),
GhiChu Nvarchar(100),
CONSTRAINT PK_DoiTra Primary key (MaPDT)  
);

CREATE TABLE HOADONCHITIET(
SKU_SP varchar(10) not null,
MaHD varchar(10) not null,
SoLuong int not null,
TienCong money,
DonGia money not null,
GiamGia money,
ThanhTien money not null
CONSTRAINT HOADONCHITIET_Pk PRIMARY KEY (MAHD, SKU_SP)
);

CREATE TABLE SKUS(
SKU varchar(10),
MaSP varchar(10),
KhoiLuong int,
DonGia money,
TienDa money,
ThanhTien money,

CONSTRAINT PK_SKUS PRIMARY KEY (SKU)
);

CREATE TABLE SKU_LOAICHATLIEU(
SKU varchar(10),
MaLCL Varchar(10)
CONSTRAINT SKU_LOAICHATLIEU_PK PRIMARY KEY (SKU, MaLCL)
);


CREATE TABLE DANHMUCSANPHAM(
MADM    VARCHAR(10) PRIMARY KEY,
TENDM   NVARCHAR(30),
MOTA    NVARCHAR(50)
)
CREATE TABLE SANPHAM(
MASP         VARCHAR(10) PRIMARY KEY,
MADM         VARCHAR(10),
TRANGTHAI    NVARCHAR(20),
TENSP        NVARCHAR(50),
MOTA         NVARCHAR(50)
)
CREATE TABLE PHIEUNHAP(
MAPN        VARCHAR(10) PRIMARY KEY,
MASP        VARCHAR(10),
SL          INT,
DONGIA      MONEY,
CONG        MONEY,
THANHTIEN   MONEY,
NGAYNHAP    DATE
)
CREATE TABLE CHATLIEU(
MACL        VARCHAR(10) PRIMARY KEY,
MASP        VARCHAR(10),
TENCL       NVARCHAR(30),
MOTA         NVARCHAR(50)
)
CREATE TABLE LOAICHATLIEU(
MALCL        VARCHAR(10) PRIMARY KEY,
MACL        VARCHAR(10),
TENLCL       NVARCHAR(30),

)
ALTER TABLE HOADON  ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) 
ALTER TABLE HOADON  ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH) 
ALTER TABLE DOITRA  ADD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE HOADONCHITIET  ADD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD) 
ALTER TABLE HOADONCHITIET  ADD FOREIGN KEY(SKU_SP) REFERENCES SKUS(SKU) 
ALTER TABLE SKUS  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
ALTER TABLE SKU_LOAICHATLIEU  ADD FOREIGN KEY(SKU) REFERENCES SKUS(SKU)
ALTER TABLE SKU_LOAICHATLIEU  ADD FOREIGN KEY(MALCL) REFERENCES LOAICHATLIEU(MALCL) 
ALTER TABLE SANPHAM  ADD FOREIGN KEY(MADM) REFERENCES DANHMUCSANPHAM(MADM) 
ALTER TABLE PHIEUNHAP  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) 
ALTER TABLE CHATLIEU  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) 
ALTER TABLE LOAICHATLIEU  ADD FOREIGN KEY(MACL) REFERENCES CHATLIEU(MACL) 



