/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.KhachHang_DAO;
import DAO.SanPham_DAO;
import Entity.KhachHang;
import Entity.SanPham;
import java.util.ArrayList;
import java.util.List;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Tiến Mạnh
 */
public class QLBH extends javax.swing.JPanel {

    List<KhachHang> listKH =new ArrayList<>();
    KhachHang_DAO khd = new KhachHang_DAO();
    SanPham_DAO spd = new SanPham_DAO();
    List<SanPham> listSP = new ArrayList<>();
    public QLBH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxTenSP = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTienCong = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        rdoTienMat = new javax.swing.JRadioButton();
        rdoPhanTram = new javax.swing.JRadioButton();
        txtGiamGia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtKhachTra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtTraLaiKhach = new javax.swing.JTextField();
        lblBangChu = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKhoiLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxHTTT = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxHinhThucMua = new javax.swing.JComboBox<>();
        cbxTrangThaiHD = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxMaKH = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Quản lý mua bán hàng");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 28, -1, -1));

        jLabel1.setText("Tên sản phẩm");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 96, -1, -1));

        cbxTenSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTenSPItemStateChanged(evt);
            }
        });
        add(cbxTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 92, 129, -1));

        jLabel17.setText("Số lượng");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 195, -1, -1));

        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });
        add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 195, 124, -1));

        jLabel18.setText("Đơn giá");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 92, -1, -1));

        txtDonGia.setEditable(false);
        add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 92, 124, -1));

        jLabel19.setText("Tiền công");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 143, -1, -1));

        txtTienCong.setEditable(false);
        add(txtTienCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 143, 124, -1));

        jLabel20.setText("Giảm giá");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 242, -1, -1));

        jLabel21.setText("Thành tiền");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 314, -1, -1));

        txtThanhTien.setEditable(false);
        add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 314, 124, -1));

        rdoTienMat.setText("Tiền mặt");
        rdoTienMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoTienMatMouseClicked(evt);
            }
        });
        add(rdoTienMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 242, -1, -1));

        rdoPhanTram.setText("Phần trăm %");
        rdoPhanTram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoPhanTramMouseClicked(evt);
            }
        });
        add(rdoPhanTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 242, -1, -1));

        txtGiamGia.setEditable(false);
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyReleased(evt);
            }
        });
        add(txtGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 242, 125, -1));

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã sản phẩm", "Tiền công", "Đơn giá", "Giảm giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDonChiTiet);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 848, 243));

        jLabel10.setText("Khách trả");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        txtKhachTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtKhachTraMouseExited(evt);
            }
        });
        add(txtKhachTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 124, -1));

        jLabel12.setText("Tổng tiền");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        txtTongTien.setEditable(false);
        add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 125, -1));

        jLabel23.setText("Trả lại khách");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        txtTraLaiKhach.setEditable(false);
        add(txtTraLaiKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 124, -1));

        lblBangChu.setText(" ");
        add(lblBangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 373, -1));

        jLabel22.setText("Bằng chữ:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        jLabel2.setText("Khối lượng");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 145, -1, -1));

        txtKhoiLuong.setEditable(false);
        add(txtKhoiLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 142, 124, -1));

        jLabel3.setText("Mã hóa đơn");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 96, -1, -1));

        txtMaHoaDon.setEditable(false);
        add(txtMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 93, 124, -1));

        jLabel8.setText("HTTT");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, -1, -1));

        cbxHTTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Thẻ tín dụng" }));
        add(cbxHTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 125, -1));

        jLabel9.setText("HT mua bán");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, -1));

        cbxHinhThucMua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mua", "Bán" }));
        add(cbxHinhThucMua, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 125, -1));

        cbxTrangThaiHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thanh toán", "Đã thanh toán" }));
        add(cbxTrangThaiHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 125, -1));

        jLabel13.setText("Trạng thái HD");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        jLabel6.setText("Mã khách hàng");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        cbxMaKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMaKHItemStateChanged(evt);
            }
        });
        add(cbxMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 129, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void fillCBX(){
        AutoCompleteDecorator.decorate(cbxTenSP);
        listKH = khd.selectAll();
        listSP = spd.selectAll();
        for (KhachHang khachHang : listKH) {
           // cbx
        }
        for (SanPham sanpham : listSP) {
            cbxTenSP.addItem(sanpham.getTenSP());
        }
        
    }
    private void cbxTenSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTenSPItemStateChanged
        //fillNameProduct();
        txtSoLuong.setText("");
        txtGiamGia.setText("");
        txtThanhTien.setText("");
    }//GEN-LAST:event_cbxTenSPItemStateChanged

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
//        try {
//            int row = tblHoaDonChiTiet.getSelectedRow();
//            if(row>0){
//                ChiTietHD cthd = listCTHD.get(row);
//                if (cthd != null) {
//                    double dongia = Double.parseDouble(txtDonGia.getText());
//                    int sl = Integer.parseInt(txtSoLuong.getText());
//                    double TTChưaGiamGia = dongia * sl;
//                    double giamGia = Double.parseDouble(txtGiamGia.getText());
//                    double thanhTien = TTChưaGiamGia - giamGia;
//                    txtThanhTien.setText(thanhTien + "");
//                    if (sl <= 0) {
//                        Msgbox.alert(this, "Số lượng là số nguyên dương");
//                        txtSoLuong.setText("");
//                        return;
//                    }
//                }
//            }
//
//            int sl = Integer.parseInt(txtSoLuong.getText());
//            if (sl <= 0) {
//                Msgbox.alert(this, "Số lượng là số nguyên dương");
//                txtSoLuong.setText("");
//                return;
//            }
//            thanhTien();
//        } catch (Exception e) {
//            Msgbox.alert(this, "Số lượng là số nguyên dương");
//            txtSoLuong.setText("");
//
//            return;
//        }
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void rdoTienMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoTienMatMouseClicked
        if (rdoTienMat.isSelected()) {
            txtGiamGia.setEnabled(true);
            txtGiamGia.setEditable(true);
        }
    }//GEN-LAST:event_rdoTienMatMouseClicked

    private void rdoPhanTramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoPhanTramMouseClicked

    }//GEN-LAST:event_rdoPhanTramMouseClicked

    private void txtGiamGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyReleased
        //thanhTien();
    }//GEN-LAST:event_txtGiamGiaKeyReleased

    private void tblHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseClicked
//        int row = tblHoaDonChiTiet.getSelectedRow();
//        ChiTietHD cthd = listCTHD.get(row);
//        setForm(cthd);
    }//GEN-LAST:event_tblHoaDonChiTietMouseClicked

    private void txtKhachTraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKhachTraMouseExited
//        float khachTra = 0;
//        try {
//            khachTra = Float.parseFloat(txtKhachTra.getText());
//            if (khachTra < 0) {
//                Msgbox.alert(this, "Số tiền trả cần tối thiểu bằng tổng tiền");
//                return;
//
//            }
//        } catch (Exception e) {
//            Msgbox.alert(this, "sai định dạng số tiền trả");
//            return;
//        }
//        float tongtien = Float.parseFloat(txtTongTien.getText());
//        float tralai = khachTra - tongtien;
//        if (tralai < 0) {
//            Msgbox.alert(this, "Số tiền trả cần tối thiểu bằng tổng tiền");
//            return;
//        }
//        txtTraLaiKhach.setText(tralai + "");
    }//GEN-LAST:event_txtKhachTraMouseExited

    private void cbxMaKHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMaKHItemStateChanged
        //fillNameCustomer();
    }//GEN-LAST:event_cbxMaKHItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxHTTT;
    private javax.swing.JComboBox<String> cbxHinhThucMua;
    private javax.swing.JComboBox<String> cbxMaKH;
    private javax.swing.JComboBox<String> cbxTenSP;
    private javax.swing.JComboBox<String> cbxTrangThaiHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBangChu;
    private javax.swing.JRadioButton rdoPhanTram;
    private javax.swing.JRadioButton rdoTienMat;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtKhachTra;
    private javax.swing.JTextField txtKhoiLuong;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTienCong;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTraLaiKhach;
    // End of variables declaration//GEN-END:variables
}
