/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChatLieu_DAO;
import DAO.loaiChatLieu_DAO;
import Entity.ChatLieu;
import Entity.LoaiChatLieu;
import Utils.Msgbox;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyChatLieu extends javax.swing.JPanel {

    private ChatLieu_DAO dao = new ChatLieu_DAO();
    private loaiChatLieu_DAO daolcl = new loaiChatLieu_DAO();
    private List<ChatLieu> list = dao.selectAll();
    private List<LoaiChatLieu> listLCL;

    /**
     * Creates new form QuanLyChatLieu
     */
    public QuanLyChatLieu() {
        initComponents();
        panLCL.setVisible(false);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaCL = new javax.swing.JTextField();
        txtTenCL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBlock = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChatLieu = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        panLCL = new javax.swing.JPanel();
        txtGiaBan = new javax.swing.JTextField();
        txtGiaMua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmaLCL = new javax.swing.JTextField();
        txtCL = new javax.swing.JTextField();
        paneLCL = new javax.swing.JScrollPane();
        tblLCL = new javax.swing.JTable();
        btnInsertLClL = new javax.swing.JButton();
        btnUpdateLCL = new javax.swing.JButton();
        btnDeleteLCL = new javax.swing.JButton();
        btnNewLCL = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTenLCL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();

        jLabel7.setText("Mô tả");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Quản lí chất liệu");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã chất liệu");

        btnBlock.setText("Khóa/Mở khóa");
        btnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlockActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên tên liệu");

        tblChatLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chất liệu", "Tên chất liệu", "Mô tả", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChatLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChatLieu);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jLabel5.setText("Giá bán");

        jLabel6.setText("Giá mua");

        jLabel8.setText("Mã CL");

        jLabel9.setText("Mã loại CL");

        txtCL.setEditable(false);

        tblLCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại CL", "Mã CL", "TenLCL", "Giá bán", "Giá mua", "Tuổi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLCL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLCLMouseClicked(evt);
            }
        });
        paneLCL.setViewportView(tblLCL);

        btnInsertLClL.setText("Thêm");
        btnInsertLClL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertLClLActionPerformed(evt);
            }
        });

        btnUpdateLCL.setText("Sửa");
        btnUpdateLCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLCLActionPerformed(evt);
            }
        });

        btnDeleteLCL.setText("Xóa");
        btnDeleteLCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLCLActionPerformed(evt);
            }
        });

        btnNewLCL.setText("New");
        btnNewLCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLCLActionPerformed(evt);
            }
        });

        jLabel10.setText("Tên LCL");

        jLabel11.setText("Tuổii");

        javax.swing.GroupLayout panLCLLayout = new javax.swing.GroupLayout(panLCL);
        panLCL.setLayout(panLCLLayout);
        panLCLLayout.setHorizontalGroup(
            panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLCLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneLCL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(panLCLLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLCLLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panLCLLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panLCLLayout.createSequentialGroup()
                        .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panLCLLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenLCL, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtmaLCL)
                                        .addComponent(txtCL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))
                            .addGroup(panLCLLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInsertLClL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteLCL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateLCL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewLCL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        panLCLLayout.setVerticalGroup(
            panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLCLLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLCLLayout.createSequentialGroup()
                        .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtmaLCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLCLLayout.createSequentialGroup()
                        .addComponent(btnInsertLClL)
                        .addGap(6, 6, 6)))
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTenLCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnUpdateLCL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewLCL))
                .addGap(40, 40, 40)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDeleteLCL)
                        .addComponent(jLabel6))
                    .addGroup(panLCLLayout.createSequentialGroup()
                        .addComponent(txtGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(18, 18, 18)
                .addGroup(panLCLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(paneLCL, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTenCL, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                        .addComponent(txtMaCL))
                                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(panLCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panLCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMaCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBlock))
                        .addGap(18, 18, 18)
                        .addComponent(btnNew)
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblLCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLCLMouseClicked
        int row = tblLCL.getSelectedRow();
        LoaiChatLieu lcl = listLCL.get(row);
        setFormLCL(lcl);
        btnInsertLClL.setVisible(false);
        txtmaLCL.setEnabled(false);
    }//GEN-LAST:event_tblLCLMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        btnThem.setVisible(true);
        ChatLieu cl = new ChatLieu();
        setForm(cl);
        txtmaLCL.setEditable(true);
        txtMaCL.setEditable(true);
        panLCL.setVisible(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChatLieuMouseClicked
        int row = tblChatLieu.getSelectedRow();
        ChatLieu cl = list.get(row);
        setForm(cl);
        if (cl.isTrangThai() == false) {
            panLCL.setVisible(false);
        } else {
            panLCL.setVisible(true);
            fillTableLCL(cl.getMaCL());
            txtCL.setText(cl.getMaCL());
            btnThem.setVisible(false);
            txtMaCL.setEditable(false);
        }


    }//GEN-LAST:event_tblChatLieuMouseClicked

    private void btnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlockActionPerformed
        int row = tblChatLieu.getSelectedRow();
        ChatLieu cl = list.get(row);
        listLCL = daolcl.selectBycl(cl.getMaCL());
        block();

    }//GEN-LAST:event_btnBlockActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnInsertLClLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertLClLActionPerformed
        insertLCL();
    }//GEN-LAST:event_btnInsertLClLActionPerformed

    private void btnNewLCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLCLActionPerformed
        txtmaLCL.setText("");
        txtTenLCL.setText("");
        txtGiaBan.setText("");
        txtGiaMua.setText("");
        btnInsertLClL.setVisible(true);
        txtmaLCL.setEnabled(true);
    }//GEN-LAST:event_btnNewLCLActionPerformed

    private void btnUpdateLCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLCLActionPerformed
        updateLCL();
    }//GEN-LAST:event_btnUpdateLCLActionPerformed

    private void btnDeleteLCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLCLActionPerformed
        deletelCl();
    }//GEN-LAST:event_btnDeleteLCLActionPerformed
    public void fillTable() {
        list = dao.selectAll();
        DefaultTableModel model = (DefaultTableModel) tblChatLieu.getModel();
        model.setRowCount(0);
        for (ChatLieu chatLieu : list) {
            Object[] row = new Object[]{
                chatLieu.getMaCL(), chatLieu.getTenCL(), chatLieu.getMoTa(),
                chatLieu.isTrangThai() == true ? "khả dụng" : "Không khả dụng"
            };
            model.addRow(row);
        }
    }

    public void fillTableLCL(String cl) {
        listLCL = daolcl.selectBycl(cl);
        DefaultTableModel model = (DefaultTableModel) tblLCL.getModel();
        model.setRowCount(0);
        for (LoaiChatLieu lcl : listLCL) {
            Object[] row = new Object[]{
                lcl.getMaLCL(), lcl.getMaCL(), lcl.getTenLCL(), new BigDecimal(lcl.getGiaBan()),
                new BigDecimal(lcl.getGiaMua()), lcl.getTuoi()
            };
            model.addRow(row);
        }
    }

    public ChatLieu getForm() {
        ChatLieu cl = new ChatLieu();
        cl.setMaCL(txtMaCL.getText());
        cl.setTenCL(txtTenCL.getText());
        cl.setMoTa(txtMota.getText());
        return cl;
    }

    public LoaiChatLieu getFormLCL() {
        LoaiChatLieu lcl = new LoaiChatLieu();
        lcl.setMaLCL(txtmaLCL.getText());
        lcl.setMaCL(txtMaCL.getText());
        lcl.setTenLCL(txtTenLCL.getText());
        lcl.setGiaBan(Double.parseDouble(txtGiaBan.getText()));
        lcl.setGiaMua(Double.parseDouble(txtGiaMua.getText()));
        lcl.setTuoi(Integer.parseInt(txtTuoi.getText()));
        return lcl;
    }

    public void setForm(ChatLieu cl) {
        txtMaCL.setText(cl.getMaCL());
        txtTenCL.setText(cl.getTenCL());
        txtMota.setText(cl.getMoTa());
    }

    public void setFormLCL(LoaiChatLieu lcl) {
        txtmaLCL.setText(lcl.getMaLCL());
        txtGiaBan.setText(new BigDecimal(lcl.getGiaBan()) + "");
        txtGiaMua.setText(new BigDecimal(lcl.getGiaMua()) + "");
        txtCL.setText(lcl.getMaCL());
        txtTenLCL.setText(lcl.getTenLCL());
        txtTuoi.setText(lcl.getTuoi() + "");
    }

    public void insert() {

        if (txtMaCL.getText().isEmpty() || txtMaCL.getText().length() > 10) {
            Msgbox.alert(this, "Không để trống mã và tối đa 10 kí tự");
            return;
        }
        for (ChatLieu chatLieu : list) {
            if (chatLieu.getMaCL().equalsIgnoreCase(txtMaCL.getText())) {
                Msgbox.alert(this, "Mã chất liệu đã tồn tại");
                return;
            }
        }
        if (txtTenCL.getText().isEmpty() || txtTenCL.getText().length() > 50) {
            Msgbox.alert(this, "Không để trống tên và tối đa 50 kí tự");
            return;
        }

        ChatLieu cl = getForm();
        dao.insert(cl);
        fillTable();
    }

    public void update() {
        if (txtMaCL.getText().isEmpty() || txtMaCL.getText().length() > 10) {
            Msgbox.alert(this, "Không để trống mã và tối đa 10 kí tự");
            return;
        }

        if (txtTenCL.getText().isEmpty() || txtTenCL.getText().length() > 50) {
            Msgbox.alert(this, "Không để trống tên và tối đa 50 kí tự");
            return;
        }
        ChatLieu cl = getForm();
        dao.update(cl);
        fillTable();
    }

    public void block() {
        int row = tblChatLieu.getSelectedRow();
        ChatLieu cl2 = list.get(row);
        if (cl2.isTrangThai() == true) {
            cl2.setTrangThai(false);
            panLCL.setVisible(false);

        } else {
            cl2.setTrangThai(true);
            panLCL.setVisible(true);
            fillTableLCL(cl2.getMaCL());
        }
        dao.block(cl2);
        fillTable();
        ChatLieu cl = new ChatLieu();
        setForm(cl);
    }

    public void deletelCl() {
        daolcl.delete(txtmaLCL.getText());
        fillTableLCL(txtCL.getText());
        txtmaLCL.setText("");
        txtTenLCL.setText("");
        txtGiaBan.setText("");
        txtGiaMua.setText("");
    }

    public void insertLCL() {

        if (txtmaLCL.getText().isEmpty() || txtmaLCL.getText().length() > 10) {
            Msgbox.alert(this, "Không để trống mã và tối đa 10 kí tự");
            return;
        }
        LoaiChatLieu lclcheck = daolcl.selectById(txtmaLCL.getText());
        if (lclcheck != null) {
            Msgbox.alert(this, "Mã chất liệu đã tồn tại");
            return;
        }
        if (txtTenLCL.getText().isEmpty() || txtTenLCL.getText().length() > 50) {
            Msgbox.alert(this, "Không để trống tên  và tối đa 50 kí tự");
            return;
        }
        for (LoaiChatLieu loaiChatLieu : listLCL) {
            if (loaiChatLieu.getMaLCL().equalsIgnoreCase(txtmaLCL.getText())) {
                Msgbox.alert(this, "Mã loại chất liệu đã tồn tại");
                return;
            }
        }
        try {
            if (txtGiaBan.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá bán");
                return;
            }

            double giaBan = Double.parseDouble(txtGiaBan.getText());
            if (giaBan < 0) {
                Msgbox.alert(this, "giá bán >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá bán");
            return;
        }
        try {
            if (txtGiaMua.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá mua");
                return;
            }
            double giamua = Double.parseDouble(txtGiaMua.getText());
            if (giamua < 0) {
                Msgbox.alert(this, "giá mua >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá mua");
            return;
        }
        try {
            if (txtTuoi.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống tuổi");
                return;
            }
            int tuoi = Integer.parseInt(txtTuoi.getText());
            if (tuoi <= 0) {
                Msgbox.alert(this, "tuổi >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Tuổi là số nguyên dương");
            return;
        }
        LoaiChatLieu lcl = getFormLCL();
        daolcl.insert(lcl);
        fillTableLCL(txtCL.getText());
    }

    public void updateLCL() {
        if (txtTenLCL.getText().isEmpty() || txtTenLCL.getText().length() > 50) {
            Msgbox.alert(this, "Không để trống tên  và tối đa 10 kí tự");
            return;
        }
        try {
            if (txtGiaBan.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá bán");
                return;
            }

            double giaBan = Double.parseDouble(txtGiaBan.getText());
            if (giaBan < 0) {
                Msgbox.alert(this, "giá bán >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá bán");
            return;
        }
        try {
            if (txtGiaMua.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá mua");
                return;
            }
            double giamua = Double.parseDouble(txtGiaMua.getText());
            if (giamua < 0) {
                Msgbox.alert(this, "giá mua >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá mua");
            return;
        }
        try {
            if (txtTuoi.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống tuổi");
                return;
            }
            int tuoi = Integer.parseInt(txtTuoi.getText());
            if (tuoi <= 0) {
                Msgbox.alert(this, "tuổi >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Tuổi là số nguyên dương");
            return;
        }
        LoaiChatLieu lcl = getFormLCL();
        daolcl.update(lcl);
        fillTableLCL(txtCL.getText());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlock;
    private javax.swing.JButton btnDeleteLCL;
    private javax.swing.JButton btnInsertLClL;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNewLCL;
    javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdateLCL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panLCL;
    private javax.swing.JScrollPane paneLCL;
    private javax.swing.JTable tblChatLieu;
    private javax.swing.JTable tblLCL;
    private javax.swing.JTextField txtCL;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaMua;
    private javax.swing.JTextField txtMaCL;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtTenCL;
    private javax.swing.JTextField txtTenLCL;
    private javax.swing.JTextField txtTuoi;
    private javax.swing.JTextField txtmaLCL;
    // End of variables declaration//GEN-END:variables
}
