/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChatLieu_DAO;
import Entity.ChatLieu;
import Utils.Msgbox;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyChatLieu extends javax.swing.JPanel {

    private ChatLieu_DAO dao = new ChatLieu_DAO();
    private List<ChatLieu> list = dao.selectAll();

    /**
     * Creates new form QuanLyChatLieu
     */
    public QuanLyChatLieu() {
        initComponents();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaCL = new javax.swing.JTextField();
        txtTenCL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        txtMota = new javax.swing.JTextField();
        txtGiaMua = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChatLieu = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();

        jLabel5.setText("Giá bán");

        jLabel6.setText("Giá mua");

        jLabel7.setText("Mô tả");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Quản lí chất liệu");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã chất liệu");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên tên liệu");

        tblChatLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chất liệu", "Tên chất liệu", "Giá bán", "Giá mua", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChatLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChatLieu);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenCL, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtMaCL, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSua)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnNew)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChatLieuMouseClicked
        int row = tblChatLieu.getSelectedRow();
        ChatLieu cl = list.get(row);
        setForm(cl);
        btnThem.setVisible(false);
        txtMaCL.setEditable(false);
    }//GEN-LAST:event_tblChatLieuMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        btnThem.setVisible(true);
        ChatLieu cl = new ChatLieu();
        setForm(cl);
        txtGiaBan.setText("");
        txtGiaMua.setText("");
        txtMaCL.setEditable(true);
        
    }//GEN-LAST:event_btnNewActionPerformed
    public void fillTable() {
        list = dao.selectAll();
        DefaultTableModel model = (DefaultTableModel) tblChatLieu.getModel();
        model.setRowCount(0);
        for (ChatLieu chatLieu : list) {
            Object[] row = new Object[]{
                chatLieu.getMaCL(), chatLieu.getTenCL(), new BigDecimal(chatLieu.getGiaBan()),
                new BigDecimal(chatLieu.getGiaMua()), chatLieu.getGiaMua(), chatLieu.getMoTa()
            };
            model.addRow(row);
        }
    }

    public ChatLieu getForm() {
        ChatLieu cl = new ChatLieu();
        cl.setMaCL(txtMaCL.getText());
        cl.setTenCL(txtTenCL.getText());
        cl.setGiaMua(Double.parseDouble(txtGiaMua.getText()) );
        cl.setGiaBan(Double.parseDouble(txtGiaBan.getText()) );
        cl.setMoTa(txtMota.getText());
        return cl;
    }

    public void setForm(ChatLieu cl) {
        txtMaCL.setText(cl.getMaCL());
        txtTenCL.setText(cl.getTenCL());
        txtGiaBan.setText( new BigDecimal(cl.getGiaBan()) + "");
        txtGiaMua.setText(new BigDecimal(cl.getGiaMua()) + "");
        txtMota.setText(cl.getMoTa());
    }

    public void insert() {
        if (txtMaCL.getText().isEmpty() || txtMaCL.getText().length() > 10) {
            Msgbox.alert(this, "Không để trống mã và tối đa 10 kí tự");
            return;
        }
        for (ChatLieu chatLieu : list) {
            if (chatLieu.getMaCL().equalsIgnoreCase(txtMaCL.getText())) {
                Msgbox.alert(this, "Mã chất liệu đã tồn tại");
                return;
            }
        }
        if (txtTenCL.getText().isEmpty() || txtTenCL.getText().length() > 50) {
            Msgbox.alert(this, "Không để trống tên và tối đa 50 kí tự");
            return;
        }
        try {
            if (txtGiaBan.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá bán");
                return;
            }
//            BigDecimal giaban= new BigDecimal(txtGiaBan.getText());
            double giaBan = Double.parseDouble(txtGiaBan.getText());
            if (giaBan < 0) {
                Msgbox.alert(this, "giá bán >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá bán");
            return;
        }
        try {
            if (txtGiaMua.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá mua");
                return;
            }
//            BigDecimal giaban= new BigDecimal(txtGiaBan.getText());
            double giamua = Double.parseDouble(txtGiaMua.getText());
            if (giamua < 0) {
                Msgbox.alert(this, "giá mua >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá mua");
            return;
        }
        if (txtMota.getText().isEmpty()) {
            Msgbox.alert(this, "Không để trống mô tả");
            return;
        }
        ChatLieu cl = getForm();
        System.out.println(cl.getGiaBan());
        dao.insert(cl);
        fillTable();
    }

    public void update() {
        if (txtMaCL.getText().isEmpty() || txtMaCL.getText().length() > 10) {
            Msgbox.alert(this, "Không để trống mã và tối đa 10 kí tự");
            return;
        }

        if (txtTenCL.getText().isEmpty() || txtTenCL.getText().length() > 50) {
            Msgbox.alert(this, "Không để trống tên và tối đa 50 kí tự");
            return;
        }
        try {
            if (txtGiaBan.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá bán");
                return;
            }
//            BigDecimal giaban= new BigDecimal(txtGiaBan.getText());
            double giaBan = Double.parseDouble(txtGiaBan.getText());
            if (giaBan < 0) {
                Msgbox.alert(this, "giá bán >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá bán");
            return;
        }
        try {
            if (txtGiaMua.getText().isEmpty()) {
                Msgbox.alert(this, "Không để trống giá mua");
                return;
            }
//            BigDecimal giaban= new BigDecimal(txtGiaBan.getText());
            double giamua = Double.parseDouble(txtGiaMua.getText());
            if (giamua <= 0) {
                Msgbox.alert(this, "giá mua >0");
                return;
            }
        } catch (Exception e) {
            Msgbox.alert(this, "Sai định dạng giá mua");
            return;
        }
        if (txtMota.getText().isEmpty()) {
            Msgbox.alert(this, "Không để trống mô tả");
            return;
        }
        ChatLieu cl = getForm();
        dao.update(cl);
        fillTable();
    }

    public void delete() {
        dao.delete(txtMaCL.getText());
        fillTable();
        ChatLieu cl = new ChatLieu();
        setForm(cl);
        txtGiaBan.setText("");
        txtGiaMua.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChatLieu;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaMua;
    private javax.swing.JTextField txtMaCL;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtTenCL;
    // End of variables declaration//GEN-END:variables
}
